### ISSUE TITLE
Remove duplicated data

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-dashboard#21]
This repository duplicates the following data from https://github.com/OpenConext/OpenConext-engineblock:

* https://github.com/OpenConext/OpenConext-dashboard/blob/master/coin-selfservice-war/src/main/resources/person_attributes.json
* https://github.com/OpenConext/OpenConext-dashboard/blob/master/coin-selfservice-war/src/main/java/nl/surfnet/coin/selfservice/util/PersonAttributeUtil.java#L73

Can be found in:

* https://github.com/OpenConext/OpenConext-engineblock/blob/master/application/configs/attributes-SURFconext.json
* https://github.com/OpenConext/OpenConext-engineblock/blob/master/application/modules/Default/Controller/LoggedIn.php#L10

Instead of having this defined multiple times all over the platform I propose adding a new repository called "OpenConext-attribute-metadata". We can version that properly and make Composer packages of that and JARs (so we can easily detect out of date definitions).

**Comment by lvonk** [comment]
I don't think this is on the top priority list. So closing this issue. Also because we are going to use shibboleth the way this is implemented will change.
