### ISSUE TITLE
Unclear what is shown in statistics graphs

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-dashboard#24]
Above the statistics graphs, the title currently is "Service usage".  It is unclear to people what that means (see eg CXT-11699).  
Please change the title, or add an explanation that the number of logins per day/week/month is shown.

**Comment by lvonk** [comment]
Any suggestions how to make it better? Also I can't seem to find CXT-11699

**Comment by baszoetekouw** [comment]
I guess adding a line "number of logins from your IdP to SP xxxx in the specified period" should help quite a lot already.
Original bugreport can be found at https://issues.surfnet.nl/browse/CXT-11699

**Comment by lvonk** [comment]
I will add that line.
