### ISSUE TITLE
Dashboard uses external webfonts

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-dashboard#26]
Dashboard uses Google webfont for its UI.  The fonts used are actually free (GPL), so we should just serve them locally, instead of giving Google a pingback for each Dashboard login.

**Comment by thijskh** [comment]
It seems Dashboard does not. Is it perhaps stats that does so?

**Comment by thijskh** [comment]
I see no third party webfonts anymore. Has this been fixed?

**Comment by baszoetekouw** [comment]
I'm still seeing a reference to ```ttps://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOFtXRa8TVwTICgirnJhmVJw.woff2``` in the current prodution Dashboard.

![image](https://cloud.githubusercontent.com/assets/1461740/18660729/6d7a12a0-7f12-11e6-9936-2e49626f228c.png)

**Comment by baszoetekouw** [comment]
and another one:
![image](https://cloud.githubusercontent.com/assets/1461740/18660809/c55a602e-7f12-11e6-9d45-ddc046cfeaeb.png)

**Comment by baszoetekouw** [comment]
The reqeusts are caused by the following in `application-1474029653300.min.css` :
```css
@import url(https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,700italic);
```

**Comment by thijskh** [comment]
@arnoutt

**Comment by arnoutt** [comment]
Thanks. Will include this in current sprint.

**Comment by s0meone** [comment]
Fixed.
