### ISSUE TITLE
Hiding SPs from being displayed

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-dashboard#33]
Hello,

I'm checking to see if there's any possible way from hiding specific SPs from being displayed in the dashboard even if it's a service an IDP can access. Basically, we're trying to hide the core OpenConext services (OIDC, Profile, Engine, Teams, etc.) from being displayed.

I know there's a `coin:ss:idp_visible_only` option, but that's aimed at single-IDP Service Providers and doesn't help in this case.

Any help would be great!

Thanks,
Andrew

**Comment by thijskh** [comment]
I can see how that would be useful. We could add an extra `coin:ss:hidden` field and those SPs would never be shown in Dashboard.

**Comment by oharsta** [comment]
Implemented. See https://github.com/OpenConext/OpenConext-dashboard/commit/8c789684c941c652df9e50386376a0db43bb6011 and https://github.com/OpenConext/OpenConext-deploy/commit/f6c756e2b9d6ef931ca854f75c0b9f39ddfeebbe
